/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AntDesignInfoCircleTwotone: typeof import('~icons/ant-design/info-circle-twotone')['default']
    AntDesignLogoutOutlined: typeof import('~icons/ant-design/logout-outlined')['default']
    AntDesignUnlockOutlined: typeof import('~icons/ant-design/unlock-outlined')['default']
    CeilProfile: typeof import('./src/components/nav-header/components/CeilProfile.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderProfile: typeof import('./src/components/nav-header/components/HeaderProfile.vue')['default']
    'IAntDesign:infoCircleTwotone': typeof import('~icons/ant-design/info-circle-twotone')['default']
    'IAntDesign:unlockTwotone': typeof import('~icons/ant-design/unlock-twotone')['default']
    IAntDesignInfoCircleTwotone: typeof import('~icons/ant-design/info-circle-twotone')['default']
    IAntDesignLogoutOutlined: typeof import('~icons/ant-design/logout-outlined')['default']
    IAntDesignUnlockOutlined: typeof import('~icons/ant-design/unlock-outlined')['default']
    IAntDesignUnlockTwotone: typeof import('~icons/ant-design/unlock-twotone')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    ILineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default']
    ILineMdMenuUnfoldRight: typeof import('~icons/line-md/menu-unfold-right')['default']
    LayoutHeader: typeof import('./src/components/layout-header/index.vue')['default']
    LineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default']
    LineMdMenuUnfoldRight: typeof import('~icons/line-md/menu-unfold-right')['default']
    NavHeader: typeof import('./src/components/nav-header/NavHeader.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/NavMenu.vue')['default']
    NavProfile: typeof import('./src/components/nav-header/components/NavProfile.vue')['default']
    Profile: typeof import('./src/components/nav-header/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserNavToolbar: typeof import('./src/components/nav-header/components/UserNavToolbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
